### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by jkriege2** [bobc/kicad-symgen#1]
Hi @bobc!

Could you bring this repo up to speed (i.e. to the version you used to update the libs in https://github.com/KiCad/kicad-library/pull/1578)? I would like to modify some symbols (basically adding a Schmitt-trigger-Symbol to the inverters with ST-input) and maybe add some more ...

Best,
JAN

**Comment by bobc** [comment]
Sorry, I had hoped I could do a quick push, but I realised I was in the middle of some changes which need cleaning, and I'm a bit short of time (I am moving house). I will try to get it updated soon even if it might be a little different to what is in kicad-library. 

I've added some new functions to allow labels like schmitt trigger to be more easily added, it turns out we have the "hysteresis" character in our Unicode font!

**Comment by bobc** [comment]
I have updated with latest version. There have been quite a few changes, I haven't done a full regression check. There are some minor changes which cause a lot of diffs, so take a while to check through.

I will also try to update the documentation and add some examples sometime. In the meantime, please raise issues for any specific errors, improvements.

**Comment by bobc** [comment]
I am presuming this issue is fixed, please re-open if not.
