### ISSUE TITLE
Generating separate GROUPs in an ELEM rather than ELEM CONTROL

### ISSUE THREAD

**Issue by mrnuke** [bobc/kicad-symgen#3]
I'm trying to model a 74HC164 shift register, which splits the first element in two halves. I'm trying to model this with the GROUP command, but it doesn't work as expected.

Expected results (left) vs actual results (right):
![hc164bs](https://user-images.githubusercontent.com/2610559/32987160-b67d0f74-cc97-11e7-8935-4fd45465a418.png)

Following descriptor was used:

```
%style IEC

COMP 74xx164 U
FPLIST
SOIC?14*
DESC 8-bit serial-in/parallel out shift register
KEYW shift register
DOC
UNIT WIDTH 500

ELEM CONTROL
8 C1/-> CI L
9 R LI L

ELEM
GROUP "&amp;" "L" ""
1 ~ I L
2 ~ I L
END-GROUP
GROUP "1D" "R" ""
SPC R
3 ~ O R
END-GROUP

ELEM
4 ~ O R

ELEM
5 ~ O R

ELEM
6 ~ O R

ELEM
10 ~ O R

ELEM
11 ~ O R

ELEM
12 ~ O R

ELEM
13 ~ O R

UNIT PWR
SPC T
SPC T
14 ~ PI T
7 ~ PI B
SPC B
SPC B
END
```

**Comment by bobc** [comment]
Looks like a bug, I will work on it. A workaround is to put the "1D" label on the element.

**Comment by bobc** [comment]
Actually groups are only implemented for pins on the left of the box, the second parameter to group is a qualifier type (clock or converted) not position. However, as a quick fix, if the pins in a group are on the right hand side then the labels will be aligned on the right hand side.

After this fix and others, the output now looks as follows \:

![image](https://user-images.githubusercontent.com/972103/33474409-585b87c4-d672-11e7-9626-fc0266f1ad82.png)

corresponding code \:
```
%style IEC
%pinlen 150

COMP 74xx164 U
FPLIST
SOIC?14*
DESC 8-bit serial-in/parallel out shift register
KEYW shift register
DOC
UNIT WIDTH 500

ELEM CONTROL LABEL "SRG8"
8 C1/→ CI L
9 R LI L

ELEM
GROUP "&amp;" - ""
1 ~ I L
2 ~ I L
END-GROUP

GROUP "1D" - ""
SPC R
3 ~ O R
END-GROUP

ELEM
4 ~ O R

ELEM
5 ~ O R

ELEM
6 ~ O R

ELEM
10 ~ O R

ELEM
11 ~ O R

ELEM
12 ~ O R

ELEM
13 ~ O R

UNIT PWR
SPC T
SPC T
14 ~ PI T

8 ~ PI B
SPC B
SPC B

END
```

Note: symgen accepts UTF8 input, and many special symbols are available in the KiCad font, so in this case I've used "→" instead of "->".

**Comment by bobc** [comment]
I am presuming this issue is fixed, please re-open if not.
